# Generated by Django 5.2.3 on 2025-07-17 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admName', models.CharField(max_length=100)),
                ('admEmail', models.EmailField(max_length=100)),
                ('admPassword', models.CharField(max_length=100)),
                ('admStatus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=100)),
                ('catSlug', models.CharField(max_length=100)),
                ('catStatus', models.BooleanField(default=True)),
                ('catSeqNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='article_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='image/')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mastercategory')),
            ],
        ),
    ]
