# Generated by Django 5.2.3 on 2025-07-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_master',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
