# Generated by Django 5.2.3 on 2025-07-22 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_article_master_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_master',
            old_name='category',
            new_name='catName',
        ),
    ]
